name: CI

on: [push, pull_request]
  paths:
    - 'nominees/*.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
      - name: install
        run:
          npm install
      - name: open PR
        run:
          node scripts/open_pr.js