name: CI

on: [push]
  # push:
  #   paths:
  #     - 'nominees/*.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: where
        run:
          pwd && ls
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
      - name: where
        run:
          pwd && ls
      - name: install
        run:
          npm install

      - name: open PR
        run:
          node scripts/open_pr.js